#FOR REFERENCE
edifici = {
"COE": "Como",
"COE04": "Como - Via Anzani",
"COE02": "Como - Via Castelnuovo",
"COE03": "Como - Via Valleggio",
"COE08": "Como - Via Zezio",
"CRG": "Cremona",
"CRG01": "Cremona - Via Sesto",
"LCF": "Lecco",
"LCF04": "Lecco - Via Ghislanzoni",
"MNI": "Mantova",
"MNI01": "Mantova - Via Scarsellini 15",
"MNI02": "Mantova - Via Scarsellini 2",
"MIB": "Milano Bovisa",
"MIB02": "Milano Bovisa - Via Durando",
"MIB01": "Milano Bovisa - Via La Masa",
"MIA": "Milano Città Studi",
"MIA11": "Milano Città Studi - Piazza Leonardo da Vinci 26",
"MIA01": "Milano Città Studi - Piazza Leonardo da Vinci 32",
"MIA03": "Milano Città Studi - Via Bassini",
"MIA02": "Milano Città Studi - Via Bonardi",
"MIA06": "Milano Città Studi - Via Colombo 40",
"MIA07": "Milano Città Studi - Via Colombo 81",
"MIA14": "Milano Città Studi - Via Golgi 20",
"MIA04": "Milano Città Studi - Via Golgi 40",
"MIA05": "Milano Città Studi - Via Mancinelli",
"MIA15": "Milano Città Studi - Via Pascoli 70",
"MIA09": "Milano Città Studi - Viale Romagna",
"PCL": "Piacenza",
"PCL04": "Piacenza - Via Scalabrini 113",
"PCL01": "Piacenza - Via Scalabrini 76"}